"""Product table added rating_sum, rating default=0

Revision ID: 23bcb87e2c71
Revises: 99ad19d9d9ce
Create Date: 2026-05-30 07:15:20.109593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bcb87e2c71'
down_revision: Union[str, Sequence[str], None] = '99ad19d9d9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating_sum', sa.Integer(), nullable=False))
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('products', 'rating_sum')
    # ### end Alembic commands ###
