"""add OrderStatus AWAITING_PAYMENT

Revision ID: 49ed2af0ae47
Revises: 87b2cf1b9e9c
Create Date: 2026-06-14 14:02:30.525022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ed2af0ae47'
down_revision: Union[str, Sequence[str], None] = '87b2cf1b9e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
