"""OrderStatus and status to string

Revision ID: 763319769584
Revises: 49ed2af0ae47
Create Date: 2026-06-14 15:26:32.865913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '763319769584'
down_revision: Union[str, Sequence[str], None] = '49ed2af0ae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_type',
               existing_type=postgresql.ENUM('CDEK', 'YANDEX', name='deliverytype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('IN_PROCESSING', 'CONFIRMED', 'AWAITING_DELIVERY', 'DELIVERY', 'AWAIT_RECEIPT', 'RECEIVED', name='orderstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('IN_PROCESSING', 'CONFIRMED', 'AWAITING_DELIVERY', 'DELIVERY', 'AWAIT_RECEIPT', 'RECEIVED', name='orderstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'delivery_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CDEK', 'YANDEX', name='deliverytype'),
               existing_nullable=False)
    # ### end Alembic commands ###
