"""add orders tables

Revision ID: 87b2cf1b9e9c
Revises: 8cde2e600112
Create Date: 2026-06-14 12:47:17.260098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b2cf1b9e9c'
down_revision: Union[str, Sequence[str], None] = '8cde2e600112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('delivery_type', sa.Enum('CDEK', 'YANDEX', name='deliverytype'), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(), nullable=False),
    sa.Column('predicted_date', sa.Date(), nullable=True),
    sa.Column('items_total_price', sa.Numeric(), nullable=False),
    sa.Column('final_price', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROCESSING', 'CONFIRMED', 'AWAITING_DELIVERY', 'DELIVERY', 'AWAIT_RECEIPT', 'RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('orders')
    # ### end Alembic commands ###
