"""phone number change to +7 format

Revision ID: 8cde2e600112
Revises: 8419ea9a8665
Create Date: 2026-06-13 17:34:09.611343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cde2e600112'
down_revision: Union[str, Sequence[str], None] = '8419ea9a8665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_to_seller', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('seller', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('application_to_seller', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
