"""Update Product, added rating, reviews_count

Revision ID: aec3ace4f81e
Revises: b5be4c3e5710
Create Date: 2026-05-23 21:59:56.312407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec3ace4f81e'
down_revision: Union[str, Sequence[str], None] = 'b5be4c3e5710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
