"""add to user and shop favourites, and shop rating fields

Revision ID: b2cedefe4b5c
Revises: 23bcb87e2c71
Create Date: 2026-06-04 04:47:46.947185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cedefe4b5c'
down_revision: Union[str, Sequence[str], None] = '23bcb87e2c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites_shops',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'shop_id')
    )
    op.add_column('shops', sa.Column('favourites_count', sa.Integer(), nullable=False))
    op.add_column('shops', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('shops', sa.Column('reviews_count', sa.Integer(), nullable=False))
    op.add_column('shops', sa.Column('rating_sum', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'rating_sum')
    op.drop_column('shops', 'reviews_count')
    op.drop_column('shops', 'rating')
    op.drop_column('shops', 'favourites_count')
    op.drop_table('favourites_shops')
    # ### end Alembic commands ###
